### ISSUE TITLE
Allow configuring the dialog height

### ISSUE THREAD

**Issue by OrBin** [bokub/home-assistant-extension#13]
Hi, very nice extension, thanks for publishing it!

It would be nice if it allowed to configure the total dialog height. 
My dashboard is higher than the extension's default and I have to scroll, which makes the experience less convenient.

**Comment by bokub** [comment]
Hello,

Unfortunately, this is not possible..

 Check out #3 and #7 for more information on the subject

**Comment by OrBin** [comment]
Hi, thank you. 
Actually I meant just configuring the height, which I now see that is already supported (up to the mentioned limits), I don't know how I missed it 🤦🏼‍♂️.
Sorry for bothering.
