### ISSUE TITLE
Addon Broken since HA v.2023.10.1

### ISSUE THREAD

**Issue by TheDescender** [bokub/home-assistant-extension#17]
Seems to be broken since latest HA update. Running HA v.2023.10.1

![image](https://github.com/bokub/home-assistant-extension/assets/43969610/9cd40249-72ae-4358-bd06-4c5a664c0fc1)

**Comment by bokub** [comment]
Please read #16

**Comment by TheDescender** [comment]
Ok after adding use_x_frame_options: false. rebooting and clearing browser cache it got fixed. Lot of breaking changes from the HA team recently, pretty frustrating. Thank for the quick response.
