### ISSUE TITLE
Works great, but not on https://

### ISSUE THREAD

**Issue by jdeath** [bokub/home-assistant-extension#2]
Works great using my internal IP without SSL, but doesn't load using my external https address

**Comment by bokub** [comment]
Can your right/click on the extension icon, inspect, then check if there are errors in the console?

**Comment by jdeath** [comment]
hmm. Ok, I'll keep playing with it. I'm using Edge, not chrome. Maybe it is
just me, using caddy reverse proxy. The extension is super cool.

**Comment by bokub** [comment]
Oh, I didn't even test on Edge, so I had no idea you could make it work so easily!

I think caddy might be the problem here...

Can you post the response headers when you visit the https version ?

For example, this is what I have: 
![image](https://user-images.githubusercontent.com/17952318/117454506-82164080-af46-11eb-9a3a-13acc87cb726.png)

**Comment by bokub** [comment]
Please go to this JSfiddle: https://jsfiddle.net/tpw63rsh/

Then, edit the `src` attribute and put the URL of your home assistant view

Finally, click the "Run" button.

Do you see your Home assistant?

- Yes: Edge problem
- No: Caddy problem

**Comment by jdeath** [comment]
Must be caddy. I see nothing in the jsfiddle (
*%3Cyour-home-assistant.com%3E*’s server IP address could not be found.)  and
get the same behavior in Chrome. I don't know how to get to the header view
you showed, but remember putting something in my caddy that prevents
iframes. It was recommended for security reasons. Tried removing it and no
change. Something with my DNS could be messed up, it happens sometimes..

I'll keep playing with it, but for now I'll just use internal IP address.
Good enough for me.

**Comment by bokub** [comment]
> *%3Cyour-home-assistant.com%3E*’s server IP address could not be found.

Are you sure you edited the `src` in the jsFiddle? :smile:

> remember putting something in my caddy that prevents iframes

What could prevent the iframe from working would be this header: `X-Frame-Options: DENY`

**Comment by rawzone** [comment]
Just to tip in with some info - HTTPS works great for me.

I'm hitting a `traefik (proxy) -> HA (hosted on a Kubernetes cluster)` via SSL and works perfectly.
