### ISSUE TITLE
Extension not loading page

### ISSUE THREAD

**Issue by Pizzarous** [bokub/home-assistant-extension#21]
It appears that my browser extension has ceased functioning properly following an update to Home Assistant. Despite configuring the 'use_x_frame_options' setting and even attempting to remove it altogether and reinstalling the extension, the issue persists.

Using the extension on Firefox.
Here are my current Home Assistant versions:

    Core: 2024.2.1
    Supervisor: 2024.01.1
    Operating System: 11.5
    Frontend: 20240207.1

The extension now only displays the Home Assistant logo without any errors appearing in the extension console debug. I've also attempted a reset and tried accessing multiple dashboards, to no avail.
![image](https://github.com/bokub/home-assistant-extension/assets/92325318/a808c641-035d-4f85-a691-3e05c461cfd3)

Could you offer any suggestions or assistance with resolving this issue?

**Comment by dapuzz** [comment]
Same happening here. In the console the error says:
` Blocked a frame with origin "https://xxxxxxx.duckdns.org" from accessing a cross-origin frame.`

Is that the same with you?

**Comment by Pizzarous** [comment]
> Same happening here. In the console the error says: ` Blocked a frame with origin "https://xxxxxxx.duckdns.org" from accessing a cross-origin frame.`
> 
> Is that the same with you?

Hey, actually nothing on console for me, no errors or warnings, only a `[HTTP/1.1 200 OK 18ms]` under Requests

**Comment by QuadrifoglioVerde** [comment]
Same here, found this: https://github.com/home-assistant/frontend/issues/19724

**Comment by bokub** [comment]
> Same here, found this: https://github.com/home-assistant/frontend/issues/19724

Good find, thanks !

**Comment by RizzleQ** [comment]
@bokub Looks like the solution is to add name="ha-main-window" to the iframe as per https://github.com/home-assistant/frontend/issues/19724#issuecomment-1946387556

Is that something you're able to edit in your extension?

**Comment by bokub** [comment]
Sure !

Can you please uninstall your browser extension, unzip the following file, install the `.crx` extension on chrome, and confirm it solves your problem ?

If yes, I'll submit it to stores monday

[home-assistant-extension.zip](https://github.com/bokub/home-assistant-extension/files/14312781/home-assistant-extension.zip)

P.S: here is a tutorial to install the `.crx`: 

![image](https://github.com/bokub/home-assistant-extension/assets/17952318/227eb105-9ea7-40ce-a97c-0ee733277317)

**Comment by Pizzarous** [comment]
> Sure !
> 
> Can you please uninstall your browser extension, unzip the following file, install the `.crx` extension on chrome, and confirm it solves your problem ?
> 
> If yes, I'll submit it to stores monday
> 
> [home-assistant-extension.zip](https://github.com/bokub/home-assistant-extension/files/14312781/home-assistant-extension.zip)
> 
> P.S: here is a tutorial to install the `.crx`:
> 
> ![image](https://private-user-images.githubusercontent.com/17952318/305459521-227eb105-9ea7-40ce-a97c-0ee733277317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTg2NjUsIm5iZiI6MTcwODA5ODM2NSwicGF0aCI6Ii8xNzk1MjMxOC8zMDU0NTk1MjEtMjI3ZWIxMDUtOWVhNy00MGNlLWE5N2MtMGVlNzMzMjc3MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE1NDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMGI3YzdiZTZjMDg4ZDUzMTA3NzQ4ODFmYjM2MTExNDJjZWViODkwNGNiNWZkMjU4Yjc4MjNmYjkzNTRlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8M1cxI8Uh2KrAfK-e095ZEEBuS5GtF9RtM6Pq6y5KSw)

If you could get me one for Firefox I can test it too !

**Comment by bokub** [comment]
Not sure it will work, but here is the version for Firefox:

[home-assistant-extension-firefox.zip](https://github.com/bokub/home-assistant-extension/files/14313149/home-assistant-extension-firefox.zip)

**Comment by Pizzarous** [comment]
> Not sure it will work, but here is the version for Firefox:
> 
> [home-assistant-extension-firefox.zip](https://github.com/bokub/home-assistant-extension/files/14313149/home-assistant-extension-firefox.zip)

you're right doesn't allow me to install unverified add ons on Firefox. But regardless of that, I installed chrome and tested that new version and everything seems to be working OK! at least on my personal usage

![image](https://github.com/bokub/home-assistant-extension/assets/92325318/eae09b69-2f86-4eb3-a254-5227efeba67e)

**Comment by RizzleQ** [comment]
> Sure !
> 
> Can you please uninstall your browser extension, unzip the following file, install the `.crx` extension on chrome, and confirm it solves your problem ?
> 
> If yes, I'll submit it to stores monday
> 
> [home-assistant-extension.zip](https://github.com/bokub/home-assistant-extension/files/14312781/home-assistant-extension.zip)
> 
> P.S: here is a tutorial to install the `.crx`:
> 
> ![image](https://private-user-images.githubusercontent.com/17952318/305459521-227eb105-9ea7-40ce-a97c-0ee733277317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDExOTMsIm5iZiI6MTcwODEwMDg5MywicGF0aCI6Ii8xNzk1MjMxOC8zMDU0NTk1MjEtMjI3ZWIxMDUtOWVhNy00MGNlLWE5N2MtMGVlNzMzMjc3MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE2MjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZGZjNjEzNzI4ZDY0YTRmODEzOTk0YjhiZWI3YzcwMzBkNGU0ZGIzOTJjMTdjNjE3ZTFmMmMzMzMwM2NkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CwplV5EeD2ZddFzLHFDci-EcpWRjbf_emwIq5op-WiM)

Unfortunately, I get this error;

![2024-02-16_11_29_57](https://github.com/bokub/home-assistant-extension/assets/87519056/9ed35fe6-03a1-46df-a55a-0d4511887548)

**Comment by rwbronco** [comment]
Tried the Chrome extension linked above by author - still doesn't fix it for me. Getting "Refused to connect" message.

Mac Ventura 13.4
Chrome Version 122.0.6261.57

**Comment by bokub** [comment]
Hello

I just submitted a new version to the [chrome web store](https://chromewebstore.google.com/detail/home-assistant/hpoiflhmfklhfcfpibmdmpeonphmdbda) and the [Firefox add-ons store](https://addons.mozilla.org/fr/firefox/addon/home-assistant/).


Could everyone please test and tell me if the issue is fixed? (make sure you install the version **0.5.0**)

Thanks

**Comment by QuadrifoglioVerde** [comment]
For me, works fine! (chrome)

**Comment by royto** [comment]
same for me on Firefox.

Thanks !!

**Comment by Pizzarous** [comment]
it works great now thanks!
