### ISSUE TITLE
Extension appears to no longer work since upgrading to 2024.2

### ISSUE THREAD

**Issue by OverZealous** [bokub/home-assistant-extension#23]
I've tried a few things, but I don't really know for sure if the issue is with the extension or something on my end.

The frame only shows the HA logo. If I load the URL directly, it always works.

I already have `use_x_frame_options: false`, and it worked until very recently. I don't have an exact date when it changed, but the upgrade to 2024.2 seems the most likely culprit.

### Versions
HA: 2024.2.2
Firefox: 122.0.1
Extension: 0.4.0

**Comment by OverZealous** [comment]
I finally figured out how to get the extension configuration to load directly, and I could see the errors in the console:

```
Uncaught (in promise) DOMException: Permission denied to access property "name" on cross-origin object
    <anonymous> get_main_window.ts:4
    <anonymous> core.h8x6ko8vS_A.js:1
core.h8x6ko8vS_A.js:1
GET
https://[REDACTED]/community/lovelace-card-mod/card-mod.js

Loading failed for the module with source “https://[REDACTED]/community/lovelace-card-mod/card-mod.js”. home:1:3866
Failed to load ‘https://[REDACTED]/community/lovelace-card-mod/card-mod.js’. A ServiceWorker intercepted the request and encountered an unexpected error. service_worker.js:1:19768
Uncaught (in promise) DOMException: Permission denied to access property "name" on cross-origin object
    63168 get_main_window.ts:4
    Webpack 7
app.Icb7AiDppIM.js:2
Uncaught (in promise) TypeError: error loading dynamically imported module: https://[REDACTED]/community/lovelace-card-mod/card-mod.js
```

So I'm guessing it's still a cross-origin issue. Sorry if this is something on my end.

**Comment by bokub** [comment]
Hello,

It looks like a duplicate of #21

**Comment by OverZealous** [comment]
It is, thank you! Sorry I missed that it was already filed. I'm not sure how I missed that.

**Comment by marketbass8-netizen** [comment]
> I've tried a few things, but I don't really know for sure if the issue is with the extension or something on my end.
> 
> The frame only shows the HA logo. If I load the URL directly, it always works.
> 
> I already have `use_x_frame_options: false`, and it worked until very recently. I don't have an exact date when it changed, but the upgrade to 2024.2 seems the most likely culprit.
> 
> ### Versions
> HA: 2024.2.2
> Firefox: 122.0.1
> Extension: 0.4.0

**Comment by marketbass8-netizen** [comment]
> I've tried a few things, but I don't really know for sure if the issue is with the extension or something on my end.
> 
> The frame only shows the HA logo. If I load the URL directly, it always works.
> 
> I already have `use_x_frame_options: false`, and it worked until very recently. I don't have an exact date when it changed, but the upgrade to 2024.2 seems the most likely culprit.
> 
> ### Versions
> HA: 2024.2.2 Firefox: 122.0.1 Extension: 0.4.0
