### ISSUE TITLE
Blocking cross-site cookies in firefox breaks the extension

### ISSUE THREAD

**Issue by rigrig** [bokub/home-assistant-extension#4]
In Firefox 88.0.1, under `about:preferences#privacy` using "Custom" -> "Cookies":  
Selecting "Cross-site cookies - includes social media cookies" or anything stricter breaks loading the Lovelace panel.

I'd really like to leave it set to blocking all 3rd-party cookies, while still using this extension. Is there any way the extension can request permission to work around this?

**Comment by MaxDucy** [comment]
Having the same issue as well

**Comment by bokub** [comment]
Could not make it work, even when I add both home assistant and the extension to the whitelist.

Sorry but I'll close this issue now.
