### ISSUE TITLE
Feature request: More height

### ISSUE THREAD

**Issue by tomlut** [bokub/home-assistant-extension#7]
Any chance we could get about double the currently available height?

**Comment by bokub** [comment]
Not possible because browser limits the height of the extension popup to 600px.

Duplicate of  #3

**Comment by bokub** [comment]
Actually, it looks like I can have an height up to 656 pixels before scrollbar appears.

I'll update the extension with this limit, but you will only gain a few pixels, you cannot double the height

**Comment by tomlut** [comment]
No worries. Sorry for not searching the closed issues first.
