### ISSUE TITLE
Not an issue, but a question...

### ISSUE THREAD

**Issue by hvddrift** [bokub/home-assistant-extension#8]
On your example you have 4 coloured dots. I assume they are for light scenes. How did you make these? I have not used HA for a long time?

![chrome_2021-06-18_11-19-51.png](https://i.imgur.com/L5zjU0N.png)

**Comment by hvddrift** [comment]
Found it as a lovelace card. RGB card

**Comment by bokub** [comment]
Yes, it's a discreet reference to another one of my projects 😉
